Repository ROCm/Tensile, pull requests merged in 2020-08, with the labels that each got.

#1123 Short program for timing hipModuleLoad function
  Tensile/Tests/hipModuleLoad_timing/Makefile
  Tensile/Tests/hipModuleLoad_timing/hipModuleLoadTiming.cpp
Labels: PerfTest

#1120 revive "CheckValue1A/B" debug function
  Tensile/KernelWriterAssembly.py
Labels: DebugHelpers, NoCI, XDLOPS

#1122 Print kernel name
  Tensile/Source/lib/include/Tensile/Debug.hpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Source/lib/source/Debug.cpp
Labels: DebugHelpers

#1129 MatrixInstruction parameter alternative format
  Tensile/BenchmarkStructs.py
  Tensile/Common.py
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_tn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_tn_inc1_asm_full.yaml
  Tensile/SolutionStructs.py
Labels: TuningScripts, XDLOPS

#1142 Refactor RunGemmKernelTests to allow configurable contraction input types
  HostLibraryTests/hip/RunGEMMKernel_test.cpp
  HostLibraryTests/testlib/include/TestUtils.hpp
  Tensile/Source/TensileTypes.h
  Tensile/Source/lib/include/Tensile/DataTypes_Int8x4.hpp
Labels: Tests

#1140 New client takes LogLevel from config.
  Tensile/ClientWriter.py
  Tensile/Common.py
  Tensile/Source/client/main.cpp
  Tensile/Source/lib/include/Tensile/Predicates.hpp
Labels: DebugHelpers

#1136 Support N = 1 for TN and NN kernel
  HostLibraryTests/configs/SolutionLibraries/KernelsLite.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLite.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteMixed.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteMixed.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteNavi.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteNavi.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsTileLite.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsTileLite.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.dat.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.yaml.gz
  Tensile/Contractions.py
  Tensile/Source/lib/configs/SolutionLibraries/KernelsLiteNavi.yaml
  Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
Labels: DeviceCodeGen

#1144 Refactor runtime contraction input type checks
  HostLibraryTests/hip/RunGEMMKernel_test.cpp
  Tensile/Source/client/include/DataInitializationTyped.hpp
  Tensile/Source/client/source/DataInitialization.cpp
  Tensile/Source/client/source/Reference.cpp
  Tensile/Source/client/source/ReferenceValidator.cpp
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  Tensile/Source/lib/include/Tensile/Utils.hpp
  Tensile/Source/lib/source/ContractionProblem.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
Labels: SolutionSelection

#1148 Fix the incorrect CSV-merge function
  Tensile/Source/client/source/CSVStackFile.cpp
  Tensile/Source/client/source/ResultFileReporter.cpp
Labels: Bug, NoCI

#1150 Allowing support for using built-in float 16. New define
  Tensile/Source/lib/include/Tensile/DataTypes_Half.hpp
Labels: Runtime
