Repository ROCm/Tensile, pull requests merged in 2020-07, with the labels that each got.

#1042 Tensile create libraries custom command
  HostLibraryTests/CMakeLists.txt
  HostLibraryTests/hip/CMakeLists.txt
  Tensile/BenchmarkProblems.py
  Tensile/ClientWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/LibraryLogic.py
  Tensile/Perf/BDAS/dgemm_kmeans.yaml
  Tensile/Perf/BDAS/dgemm_pca.yaml
  Tensile/Perf/TRANSFORMER/sgemm_xdlops_nt.yaml
  Tensile/TensileCreateLibrary.py
  Tensile/Utilities/merge.py
  Tensile/cmake/TensileConfig.cmake
Labels: BuildPackaging

#1047 fix LdsBlockSizePerPad=-1 assignment
  Tensile/Common.py
  Tensile/SolutionStructs.py
Labels: XDLOPS

#1025 SIA3 support to schedule more GR,LW instructions between mfma
  Tensile/KernelWriter.py
Labels: XDLOPS

#1029 storeRemap: support free 0 direction MIWaveGroup
  Tensile/KernelWriterAssembly.py
  Tensile/SolutionStructs.py
Labels: GFX9Code, XDLOPS

#1059 Move fp16 code entirely to components
  Tensile/Code.py
  Tensile/Common.py
  Tensile/Component.py
  Tensile/Components/MAC_F16.py
  Tensile/Components/MAC_F16_HPA.py
  Tensile/Components/Priority.py
  Tensile/Components/Signature.py
  Tensile/Components/__init__.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/Perf/DLRM/sgemm_xdlops.yaml
  Tensile/Perf/DLRM/sgemm_xdlops_nn_terabyte.yaml
  Tensile/Perf/DLRM/sgemm_xdlops_nt.yaml
  Tensile/Perf/DLRM/sgemm_xdlops_nt_terabyte.yaml
  Tensile/Perf/DLRM/sgemm_xdlops_tn_terabyte.yaml
  Tensile/Perf/TRANSFORMER/sgemm_xdlops.yaml
  Tensile/Tensile.py
  Tensile/Tests/conftest.py
  Tensile/Tests/pre_checkin/mfma/c-tile-reuse-no-nll.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_bfloat16_gemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm_mi32x32x1x2.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm_mi32x32x2x1.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_todo.yaml
  Tensile/Tests/unit/test_Component.py
  Tensile/Tests/unit/test_Priority.py
  pytest.ini
Labels: DeviceCodeGen, GFX10Code, GFX9Code

#1049 wider local read and use 1 LDS buffer with prefetch global read
  Tensile/Common.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/SolutionStructs.py
  Tensile/Tests/pre_checkin/mfma/1LDSB.yaml
  Tensile/Tests/pre_checkin/mfma/wider_local_read.yaml
Labels: XDLOPS

#1056 reject nonMI with SIA2 or SIA3
  Tensile/SolutionStructs.py
Labels: NoCI, XDLOPS

#1018 host-side assertion to check bufferload/bufferstore offset limit
  Tensile/Configs/rocblas_dgemm_bufferload_limit.yaml
  Tensile/Configs/rocblas_hgemm_bufferload_limit.yaml
  Tensile/Configs/rocblas_sgemm_bufferload_limit.yaml
  Tensile/Contractions.py
  Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  Tensile/Source/lib/include/Tensile/Serialization/ContractionSolution.hpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Tests/extended/bufferload_offset/rocblas_dgemm_bufferload_limit.yaml
  Tensile/Tests/extended/bufferload_offset/rocblas_sgemm_bufferload_limit.yaml
Labels: DeviceCodeGen, Tensor

#1044 More tuning script changes
  tuning/automation/ExtractSizes.py
  tuning/automation/GenerateTuningConfigurations.py
  tuning/automation/TuningConfiguration.py
  tuning/scripts/master_tuning_script.sh
  tuning/scripts/provision_tuning.sh
Labels: TuningScripts

#1074 [HotFix] fix create library error with old client
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
Labels: Hotfix, XDLOPS

#1075 Merge script update
  Tensile/Utilities/merge.py
Labels: NoCI

#1060 Pipelined store for MI kernels
  Tensile/KernelWriterAssembly.py
  Tensile/Tests/pre_checkin/mfma/hpa_bfloat16_gemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm_mi32x32x1x2.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm_mi32x32x2x1.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_todo.yaml
Labels: DeviceCodeGen, GFX9Code, XDLOPS

#1088 fix alternateTypes bug in tuning scripts
  tuning/automation/ExtractSizes.py
Labels: Bug, NoCI, TuningScripts

#1100 Fix: reusable vgpr up to next occupancy threshold
  Tensile/KernelWriterAssembly.py
  Tensile/Tests/unit/test_KernelWriterAssembly.py
Labels: Bug, Tests
