Repository ROCm/Tensile, pull requests merged in 2020-11, with the labels that each got.

#1174 Add support for hpa fp16 in fp32 out
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.dat.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.yaml.gz
  Tensile/Common.py
  Tensile/Configs/rocblas_hpa_bf16s_gemm_tn_asm_test.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_gemm_inc1_hip.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_gemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_gemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_gemm_tn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_hip_lite.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_hip_single_kernel.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_tn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16s_tn_inc2_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_asm_lite.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_asm_single_kernel.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_hip_lite.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_inc1_hip.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_nn_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_nt_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_tn_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_tn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hsgemm_tt_asm_full.yaml
  Tensile/Configs/rocblas_hsgemm_asm_lite.yaml
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Tests/pre_checkin/bfloat16/bfloat16s_hpa_source_nn.yaml
  Tensile/Tests/pre_checkin/bfloat16/bfloat16s_hpa_source_nt.yaml
  Tensile/Tests/pre_checkin/bfloat16/bfloat16s_hpa_source_tn.yaml
  Tensile/Tests/pre_checkin/bfloat16/bfloat16s_hpa_source_tt.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_asm_nn.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_asm_nt.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_asm_tn.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_asm_tt.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_iu2_asm_nn.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_iu2_asm_nt.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_iu2_asm_tn.yaml
  Tensile/Tests/pre_checkin/hsgemm_hpa_iu2_asm_tt.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_bfloat16s_gemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_hsgemm_asm.yaml
Labels: DeviceCodeGen, Tests, XDLOPS

#1217 fix GSU bug: PostGSU kernel refer to Nan data of C matrix even when b…
  Tensile/KernelWriterConversion.py
Labels: Bug, Hotfix

#1222 add CHANGELOG.md
  CHANGELOG.md
Labels: Documentation, NoCI

#1225 add merge=union gitattributes for CHANGELOG.md
  .gitattributes
Labels: NoCI

#1214 Instruction scheduling to reduce LDS by half in TN problems
  .gitignore
  Tensile/Code.py
  Tensile/Common.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_split_lds.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_split_lds.yaml
Labels: DeviceCodeGen, GFX9Code, XDLOPS

#1189 Update arcturus tuning configs for fp16/bf16
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_inc1_hip.yaml
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_bfloat16_gemm_tn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_inc1_hip.yaml
  Tensile/Configs/rocblas_hpa_hgemm_nn_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_nt_inc1_asm_full.yaml
  Tensile/Configs/rocblas_hpa_hgemm_tn_inc1_asm_full.yaml
Labels: NoCI, TuningFiles

#1227 Hotfix for PR #1214: count the right instruction type under different scheduling
  Tensile/KernelWriterAssembly.py
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_asm.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_split_lds.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_asm.yaml
Labels: Bug, DeviceCodeGen

#1226 Update test config to avoid large memory usage
  Tensile/Configs/rocblas_dgemm_bufferload_limit.yaml
  Tensile/Configs/rocblas_sgemm_bufferload_limit.yaml
  Tensile/Tests/extended/bufferload_offset/rocblas_dgemm_bufferload_limit.yaml
  Tensile/Tests/extended/bufferload_offset/rocblas_sgemm_bufferload_limit.yaml
Labels: Tests
