Repository ROCm/Tensile, pull requests merged in 2020-10, with the labels that each got.

#1167 Prefetch Global Read 2
  Tensile/Common.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
Labels: GFX9Code

#1116 New BoundsCheck design: guard page
  HostLibraryTests/client/DataInitialization_test.cpp
  Tensile/ClientWriter.py
  Tensile/Common.py
  Tensile/Source/client/include/DataInitialization.hpp
  Tensile/Source/client/include/DataInitializationTyped.hpp
  Tensile/Source/client/include/ReferenceValidator.hpp
  Tensile/Source/client/main.cpp
  Tensile/Source/client/source/DataInitialization.cpp
  Tensile/Source/client/source/ReferenceValidator.cpp
Labels: Tests

#1186 Print warning for unexpected rejection during TensileCreateLibrary
  Tensile/SolutionStructs.py
  Tensile/TensileCreateLibrary.py
Labels: DebugHelpers

#1169 Refactor codes for data-type. Reserve the possibility of <H,H,S> version HPA
  HostLibraryTests/client/DataInitialization_test.cpp
  HostLibraryTests/hip/RunGEMMKernel_test.cpp
  Tensile/ClientWriter.py
  Tensile/Contractions.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/SolutionWriter.py
  Tensile/Source/client/include/DataInitializationTyped.hpp
  Tensile/Source/client/main.cpp
  Tensile/Source/client/source/ClientProblemFactory.cpp
  Tensile/Source/client/source/DataInitialization.cpp
  Tensile/Source/client/source/Reference.cpp
  Tensile/Source/client/source/ReferenceValidator.cpp
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  Tensile/Source/lib/include/Tensile/DataTypes.hpp
  Tensile/Source/lib/source/ContractionProblem.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Tests/pre_checkin/hgemm_hpa_asm_f32_alphabeta_nn.yaml
  Tensile/Tests/pre_checkin/hgemm_hpa_asm_f32_alphabeta_nt.yaml
  Tensile/Tests/pre_checkin/hgemm_hpa_asm_f32_alphabeta_tn.yaml
  Tensile/Tests/pre_checkin/hgemm_hpa_asm_f32_alphabeta_tt.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_f32_alphabeta_asm.yaml
  Tensile/Tests/pre_checkin/source/test_hgemm_hpa.yaml
Labels: GFX9Code, Runtime

#1200 [Hotfix] PK kernel is never picked in rocBLAS, causing perf. drop in dgemm
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
Labels: Hotfix

#1177 Merge script fix and enhancements
  Tensile/Tests/unit/test_mergeLogic.py
  Tensile/Utilities/merge.py
Labels: Bug, Tests, TuningScripts

#1190 Automation for documentation
  tuning/automation/GenerateTuningConfigurations.py
  tuning/scripts/analyze-results.sh
  tuning/scripts/master_tuning_script.sh
  tuning/scripts/provision_tuning.sh
  tuning/scripts/provision_verification.sh
  tuning/scripts/run_validation.sh
  tuning/scripts/stage_tuning.sh
  tuning_docs/README.md
  tuning_docs/examples/example_arcturus_tuning.yaml
  tuning_docs/examples/example_vega10_tuning.yaml
  tuning_docs/examples/example_vega20_tuning.yaml
  tuning_docs/install_latex.sh
  tuning_docs/tensile_tuning.tex
Labels: Documentation, TuningScripts
