Repository ROCm/Tensile, pull requests merged in 2020-09, with the labels that each got.

#1149 Fix master tuning script
  tuning/automation/ExtractSizes.py
  tuning/automation/GenerateTuningConfigurations.py
  tuning/automation/PerformanceAnalysis.py
  tuning/scripts/master_tuning_script.sh
  tuning/scripts/provision_tuning.sh
  tuning/scripts/provision_verification.sh
Labels: TuningScripts

#1081 Benchmark tuning parts
  Tensile/BenchmarkProblems.py
  Tensile/BenchmarkStructs.py
  Tensile/ClientWriter.py
  Tensile/Common.py
  Tensile/LibraryIO.py
  Tensile/LibraryLogic.py
  Tensile/TensileCreateLibrary.py
  Tensile/Tests/test_data/unit/library_data/hardcodedParameters.yaml
  Tensile/Tests/test_data/unit/library_data/initialSolutionParameters.yaml
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx1010.hsaco
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx1011.hsaco
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx803.hsaco
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx900.hsaco
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx906.hsaco
  Tensile/Tests/test_data/unit/library_data/library/Kernels.so-000-gfx908.hsaco
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary.yaml
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx1010.co
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx1011.co
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx803.co
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx900.co
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx906.co
  Tensile/Tests/test_data/unit/library_data/library/TensileLibrary_gfx908.co
  Tensile/Tests/test_data/unit/library_data/library/metadata.yaml
  Tensile/Tests/test_data/unit/library_data/problemType.yaml
  Tensile/Tests/test_data/unit/solutions/solutions_nn_3.yaml
  Tensile/Tests/unit/test_Common.py
  Tensile/Tests/unit/test_TensileCreateLibrary.py
  Tensile/Tests/yaml_only/test_config.py
  Tensile/a.out
Labels: TuningScripts

#1125 PersistentKernel with Prefetch
  HostLibraryTests/ProjectedPerformance_test.cpp
  HostLibraryTests/configs/SolutionLibraries/KernelsLite.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLite.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteMixed.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteMixed.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteNavi.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsLiteNavi.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsTileLite.dat.gz
  HostLibraryTests/configs/SolutionLibraries/KernelsTileLite.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/SampleTensileKernels.dat.gz
  HostLibraryTests/configs/SolutionLibraries/SampleTensileKernels.yaml.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.dat.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.yaml.gz
  HostLibraryTests/llvm/LLVMYAMLContraction_test.cpp
  HostLibraryTests/sample_library.yaml
  Tensile/Common.py
  Tensile/Components/Signature.py
  Tensile/Contractions.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Source/client/source/SolutionIterator.cpp
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  Tensile/Source/lib/include/Tensile/Serialization/ContractionSolution.hpp
  Tensile/Source/lib/source/ContractionProblem.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Tests/pre_checkin/regression/persistent_kernel.yaml
Labels: DeviceCodeGen, GFX9Code, XDLOPS

#1157 fix ResultFileReporter merger when best-solution=true
  Tensile/Source/client/source/ResultFileReporter.cpp
Labels: Bug, NoCI

#1135 Kernel short circuit alpha zero
  HostLibraryTests/hip/RunGEMMKernel_test.cpp
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/Source/client/source/Reference.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
Labels: DeviceCodeGen

#1171 Fixing the logic for testing if (alpha == 1) for OptNLL
  Tensile/KernelWriterAssembly.py
Labels: Bug, GFX9Code
