Repository ROCm/Tensile, pull requests merged in 2020-12, with the labels that each got.

#1240 Fix the misleading/outdated comments for DataInitType
  Tensile/ClientWriter.py
  Tensile/Common.py
  Tensile/Source/client/include/DataInitialization.hpp
Labels: Documentation, NoCI

#1146 Tensile integration test
  .jenkins/common.groovy
  .jenkins/integration.groovy
  Tensile/ClientWriter.py
  Tensile/Common.py
  Tensile/SolutionStructs.py
  Tensile/TensileCreateLibrary.py
  Tensile/Tests/integration/test_integration.py
  Tensile/Tests/yaml_only/test_config.py
  a.out
  pytest.ini
Labels: Tests, TuningScripts

#1242 Use pytest fixtures to setup integration test logic yamls
  Tensile/Tests/integration/test_integration.py
Labels: Tests

#1248 Fix bugs of tail-loop branch label, and LR addr restore
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_split_lds.yaml
  Tensile/Tests/pre_checkin/mfma/sgemm_split_lds.yaml
Labels: Bug, XDLOPS

#1213 PersistentKernel Refine: Support PKn1, EPS, optimize LW-vmcnt, and sMagicDiv2
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.dat.gz
  HostLibraryTests/configs/SolutionLibraries/rocBLAS_Full.yaml.gz
  Tensile/Common.py
  Tensile/Components/Signature.py
  Tensile/Contractions.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  Tensile/Source/lib/source/ContractionProblem.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Tests/pre_checkin/regression/persistent_kernel.yaml
Labels: GFX9Code, XDLOPS

#1249 TensileCreateLibraryFiles: automatically create target for build time library generation
  HostLibraryTests/CMakeLists.txt
  HostLibraryTests/hip/CMakeLists.txt
  Tensile/cmake/TensileConfig.cmake
Labels: BuildPackaging
