Repository ROCm/Tensile, pull requests merged in 2021-03, with the labels that each got.

#1295 Tuning archiving for rocBLAS-internal 539 and 547
  Tensile/Configs/miopen/archives/megatron/2021-02-04/2_BenchmarkData.tar.gz
  Tensile/Configs/miopen/archives/megatron/2021-02-04/configs/vega20_hgemm_nn_hbh.yaml
  Tensile/Configs/miopen/archives/megatron/2021-02-04/configs/vega20_hgemm_nt_hbh.yaml
  Tensile/Configs/miopen/archives/megatron/2021-02-04/configs/vega20_hgemm_tn_hbh.yaml
  Tensile/Configs/miopen/archives/megatron/2021-02-04/exact/vega20_Cijk_Ailk_Bjlk_HBH.yaml
  Tensile/Configs/miopen/archives/megatron/2021-02-04/exact/vega20_Cijk_Ailk_Bljk_HBH.yaml
  Tensile/Configs/miopen/archives/megatron/2021-02-04/exact/vega20_Cijk_Alik_Bljk_HBH.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/2_BenchmarkData.tar.gz
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/configs/arcturus_sgemm_nn_sb.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/configs/arcturus_sgemm_nt_sb.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/configs/arcturus_sgemm_tn_sb.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/exact/arcturus_Cijk_Ailk_Bjlk_SB.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/exact/arcturus_Cijk_Ailk_Bljk_SB.yaml
  Tensile/Configs/miopen/archives/resnext3d/2021-02-10/exact/arcturus_Cijk_Alik_Bljk_SB.yaml
Labels: NoCI

#1305 Fix: TensileCreateLibrary relative output path crash
  CHANGELOG.md
  Tensile/TensileCreateLibrary.py
Labels: Bug

#1306 New Python unit tests for predicates and predicate libraries
  Tensile/Tests/unit/test_HardwarePredicates.py
  Tensile/Tests/unit/test_PerfMetricPredicates.py
Labels: Tests

#1312 LibraryIO.py refactor and tests
  Tensile/BenchmarkProblems.py
  Tensile/ClientWriter.py
  Tensile/GenerateSummations.py
  Tensile/LibraryIO.py
  Tensile/LibraryLogic.py
  Tensile/Tensile.py
  Tensile/TensileCreateLibrary.py
  Tensile/Tests/integration/test_integration.py
  Tensile/Tests/unit/test_LibraryIO.py
  Tensile/Tests/unit/test_TensileCreateLibrary.py
  Tensile/Tests/yaml_only/test_config.py
Labels: Tests

#1319 Fix an error: invalid register class: vgpr tuples must be 64 bit aligned
  Tensile/KernelWriterAssembly.py
Labels: GFX9Code
