Repository ROCm/Tensile, pull requests merged in 2021-01, with the labels that each got.

#1246 Tensile cluster tuning tool
  Tensile/BenchmarkSplitter.py
  Tensile/Configuration.py
  Tensile/TensileBenchmarkCluster.py
  Tensile/TensileBenchmarkClusterScripts.py
  Tensile/Tests/unit/test_Configuration.py
  Tensile/Utilities/merge.py
  Tensile/bin/TensileBenchmarkCluster
  docker/dockerfile-tensile-tuning-slurm
  setup.py
Labels: Tests, TuningScripts

#1185 MatrixInstruction for general int8
  HostLibraryTests/DataTypes_test.cpp
  Tensile/Code.py
  Tensile/Common.py
  Tensile/Configs/mfma/mfma_igemm_lite_test.yaml
  Tensile/Configs/mfma/mfma_igemm_nn_asm_full.yaml
  Tensile/Configs/mfma/mfma_igemm_nt_asm_full.yaml
  Tensile/Configs/mfma/mfma_igemm_tn_asm_full.yaml
  Tensile/Configs/mfma/mfma_igemm_tt_asm_full.yaml
  Tensile/DataType.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Source/client/include/DataInitialization.hpp
  Tensile/Source/client/include/DataInitializationTyped.hpp
  Tensile/Source/client/include/LogReporter.hpp
  Tensile/Source/client/source/DataInitialization.cpp
  Tensile/Source/client/source/Reference.cpp
  Tensile/Source/client/source/ReferenceValidator.cpp
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  Tensile/Source/lib/include/Tensile/DataTypes.hpp
  Tensile/Source/lib/include/Tensile/DataTypes_Int8.hpp
  Tensile/Source/lib/source/ContractionProblem.cpp
  Tensile/Source/lib/source/ContractionSolution.cpp
  Tensile/Source/lib/source/DataTypes.cpp
  Tensile/Tests/pre_checkin/mfma/hpa_igemm_i8_asm.yaml
Labels: DeviceCodeGen, GFX9Code, Runtime, XDLOPS

#1255 General cleaning and improvements to tuning document
  tuning_docs/tensile_tuning.tex
Labels: Documentation, NoCI
