Repository ROCm/Tensile, pull requests merged in 2021-06, with the labels that each got.

#1367 CHANGELOG.md update for ROCm 4.4
  CHANGELOG.md
Labels: NoCI

#1370 fix bug of ScheduleIterAlg 2,3 case for aldebaran bf16_1k MatrixInstr…
  Tensile/KernelWriter.py
Labels: Bug, DeviceCodeGen, GFX9Code, XDLOPS

#1355 Split LDS optimization
  Tensile/Common.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/SolutionStructs.py
  Tensile/Tests/conftest.py
  Tensile/Tests/pre_checkin/mfma/hpa_hgemm_split_lds.yaml
  Tensile/Tests/pre_checkin/mfma/hpa_igemm_i8_split_lds.yaml
Labels: DeviceCodeGen
