Repository ROCm/Tensile, pull requests merged in 2022-06, with the labels that each got.

#1530 Apply clang-format
  Tensile/Source/lib/include/Tensile/Distance.hpp
  Tensile/Source/lib/include/Tensile/Serialization/MatchingLibrary.hpp
Labels: noExtendedCI

#1533 DirectToVgpr support for SGEMM + bug fixes
  Tensile/Components/LocalRead.py
  Tensile/Components/LraTileAssignment.py
  Tensile/Components/NotLocalFullTileElements.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/SolutionStructs.py
  Tensile/Tests/pre_checkin/direct_to_vgpr/dtv_sgemm_lite.yaml
Labels: XDLOPS

#1538 Apply clang-format
  Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  Tensile/Source/lib/source/llvm/YAML.cpp
Labels: noExtendedCI

#1539 Update copyright githook
  .githooks/pre-commit
Labels: NoCI

#1542 Update changelog for 4.34.0
  CHANGELOG.md
Labels: NoCI
