Repository ROCm/Tensile, pull requests merged in 2022-08, with the labels that each got.

#1324 Re-enable HardwareMonitor for gfx90a
  Tensile/Common.py
Labels: ci:no-ccache

#1576 Update CHANGELOG.md for ROCm 5.3
  CHANGELOG.md
Labels: NoCI

#1574 Async DMA support for Transpose Data Layout (ThreadSeparateGlobalRead support) + small bug fix
  Tensile/Common.py
  Tensile/Components/LocalRead.py
  Tensile/Components/LraTileAssignment.py
  Tensile/KernelWriter.py
  Tensile/KernelWriterAssembly.py
  Tensile/KernelWriterSource.py
  Tensile/SolutionStructs.py
  Tensile/Tests/extended/direct_to_lds/dtl_tsgr_hgemm.yaml
  Tensile/Tests/extended/direct_to_lds/dtl_tsgr_sgemm.yaml
  Tensile/Tests/pre_checkin/direct_to_lds/dtl_tsgr_dgemm.yaml
Labels: XDLOPS
