Repository ROCm/Tensile, pull requests merged in 2024-07, with the labels that each got.

#1953 Disable failing rhel9 tests
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: gfx94x

#1950 Add gfx12 support
  Tensile/AsmCaps.py
  Tensile/Common.py
  Tensile/KernelWriterSource.py
Labels: gfx12

#1959 Restrict XCC mapping to gfx942
  Tensile/SolutionStructs.py
Labels: ci:extended

#1972 Remove deprecated flag from profiling job
  .jenkins/profiling.groovy
Labels: ci:profiling

#1978 Restore rhel testing
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: gfx94x

#1949 Add contributor and developer guide
  CONTRIBUTING.md
  CONTRIBUTING.rst
  Tensile/TensileCreateLibrary.py
  Tensile/Utilities/parse_results.py
  docs/conf.py
  docs/src/api-reference/TensileCreateLibrary.rst
  docs/src/cli-reference.rst
  docs/src/concepts.rst
  docs/src/contributor-guide.rst
  docs/src/developer-guide.rst
  docs/src/getting-started.rst
  requirements.in
  requirements.txt
  tasks.py
  tox.ini
Labels: Documentation, ci:docs-only

#1993 Do not use version specific requirements.txt
  requirements.txt
Labels: NoCI

#1994 Update changelog for 4.42.0
  CHANGELOG.md
Labels: NoCI
