Repository ROCm/Tensile, pull requests merged in 2025-01, with the labels that each got.

#2074 Fix argument list too long error
  Tensile/BuildCommands/AssemblyCommands.py
Labels: ci:extended

#2078 Update copyright date to 2025
  LICENSE.md
Labels: NoCI, ci:docs-only

#2056 Documentation updates
  docs/sphinx/_toc.yml.in
  docs/src/conceptual/introduction.rst
  docs/src/conceptual/solution-selection-catalogs.rst
  docs/src/index.rst
  docs/src/install/installation.rst
  docs/src/reference/nomenclature.rst
  tuning/README.md
Labels: Documentation, ci:docs-only
